name: Deploy to AWS EC2 with CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip the application
        run: zip -r app.zip . -x "*.git*"

      - name: Upload to S3
        run: aws s3 cp app.zip s3://flaskapp-deploy-bucket/app.zip
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to CodeDeploy
        run: aws deploy create-deployment \
              --application-name flaskapp \
              --deployment-group-name flaskapp-deployment-group \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --s3-location bucket=flaskapp-deploy-bucket,bundleType=zip,key=app.zip
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

